defaults:
  - base_dataset
  - view_sampler: all

name: omniscene
roots: [datasets/omniscene]

original_image_shape: [224, 400]
cameras_are_circular: false

baseline_min: 1e-3
baseline_max: 1e2
max_fov: 100.0
avg_pose: false

rescale_to_1cube: true
make_baseline_1: false
intr_augment: true